### ISSUE TITLE
Should Resources be allowed to override the searchOrCreate

### ISSUE THREAD

**Issue by bcooksey** [zapier/zapier-platform-schema#13]
Currently the schema allows a resource to [define a searchOrCreate](https://github.com/zapier/zapier-platform-schema/blob/0589e09985a87a6967d1eca27bfb55b2b93f7dd6/lib/schemas/ResourceSchema.js#L51-L54) property, which looks like [this](https://github.com/zapier/zapier-platform-schema/blob/0589e09985a87a6967d1eca27bfb55b2b93f7dd6/lib/schemas/ResourceMethodSearchOrCreateSchema.js).

The issue is that the regular `SearchOrCreate` schema is like [this](https://github.com/zapier/zapier-platform-schema/blob/0589e09985a87a6967d1eca27bfb55b2b93f7dd6/lib/schemas/SearchOrCreateSchema.js), just defining keys of existing searches and creates to use. 

Open Questions:

 * Should a resource be allowed to overwrite this at all?
 * If so, should it be:
    * Restricted to settings keys of other searches and creates
    * Define entire operations for search and for create
    * Define a single operation? (Zapier side would need to be edited to support this)

**Comment by bcooksey** [comment]
My two cents is that we completely nuke this property from the resource. If you use a resource and define the search and the create, it seems odd that there would be a completely different mechanism to do those two things in sequence.

The one possibility that makes sense is an API that provides a get-or-create type call. However, as already mentioned, Zapier doesn't support that flow right now. It wouldn't be impossible, but I want to hear of more use cases from actual APIs before we implement that.

**Comment by BrunoBernardino** [comment]
FWIW I agree with nuking.
