### ISSUE TITLE
Parent key is missing from FieldSchema

### ISSUE THREAD

**Issue by ianchadwick** [zapier/zapier-platform-schema#15]
Using the Zapier interface I can set the Parent key to group fields and keep things nice and tidy.

This is currently missing from the FieldSchema.

**Comment by BrunoBernardino** [comment]
Hi @ianchadwick I'm sorry for the terribly late comment here (we don't actively monitor public issues on this repo, only `-cli`). We do have a [`children`](https://github.com/zapier/zapier-platform-schema/blob/master/docs/build/schema.md#fieldschema) property for fields in CLI. Have you looked into that?
