### ISSUE TITLE
Support Search-Powered Fields

### ISSUE THREAD

**Issue by bcooksey** [zapier/zapier-platform-schema#2]
Zapier has a concept of a field that is intended to be populated by the output of a search (called a "Search Connector" in the V2 Platform). For example, an "Add Tag to Contact" Create needs a reference to the contact to add the tag to. When defining the field on the Create, there needs to be a way to link the field to a Search that is defined on the app so that Zapier can give the field some special treatment in the Zapier UI.

The link should work similar to a Dynamic Dropdown. With the dropdowns, a field in one Trigger/Create has a [reference](https://github.com/zapier/zapier-platform-schema/blob/442214b5b3993082bba0fafa75182d112d7e7da7/lib/schemas/FieldSchema.js#L69-L72) to another Trigger to populate it's options. Here, the field contains a reference to a Search so that Zapier 1) has a hint of what the user needs to map into the field and 2) can even suggest the Search step to add to complete the Zap.

**Comment by bryanhelmig** [comment]
Makes sense to me, do we want a resource ref which exists already or something a bit different?

**Comment by bcooksey** [comment]
I think it makes sense to go with a resource ref. If you can search to find a thing and associate it with another thing, that seems to imply a relational structure, which resources nicely fit.

**Comment by bcooksey** [comment]
Thinking about this a bit, maybe a name like `searchFiller` or something for the property. What could be nice is that we can swap `dynamic` to then be `choicesFiller` or whatever and that would also knock out #4.

**Comment by bryanhelmig** [comment]
I don't mind the word `dynamic` if it just means "determined lazily" - maybe [`dynamic`](https://github.com/zapier/zapier-platform-schema/blob/442214b5b3993082bba0fafa75182d112d7e7da7/lib/schemas/FieldSchema.js#L69-L72) can be `dynamicChoices`? Kind of feels like you could provide a function there then instead of just a reference...

**Comment by BrunoBernardino** [comment]
I think `searchConnector` makes a lot of sense even in the context of a new dev in Zapier (for an existing dev, it's the terminology we already use). You're connecting a search to a field.

Also I don't understand the difference between providing a function or resource ref. Shouldn't it be a reference to a search, and the search _can_ have a function or a resource already?

**Comment by bcooksey** [comment]
@BrunoBernardino resource reference means the app has to define it like `searchConnector: 'contact' or `'contact.id.name'`. Like you said, it's just a string that tells us which resource to look to for powering the search step that eventually fills in this value.

**Comment by BrunoBernardino** [comment]
Oh, was thinking `resource` as in the `resources` we have for the easier RESTful implementations. Damn name collisions 😄
