### ISSUE TITLE
When a field's children property is used, others should be forbidden

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-schema#21]
When a field definition has `children` several other properties should throw an error. For example `list:true` is not compatible as https://secure.helpscout.net/conversation/377971902/554113/?folderId=20363 found.

I don't know if we already have a mechanism to define and validate mutual exclusive field properties/values. If we haven't, it may be something to consider adding as it can prevent some common issues with app definitions.

/cc @zapier/platform

**Comment by BrunoBernardino** [comment]
Tracking in PR.
