### ISSUE TITLE
Add support for REST Hooks that can poll for sample data

### ISSUE THREAD

**Issue by bcooksey** [zapier/zapier-platform-schema#3]
A common pattern with existing apps on Zapier is to create Triggers that are powered by REST Hooks, but are also configured with an endpoint that can be used to fetch a list of results. This comes in handy when a user is setting up a Zap and needs to fetch a sample record. Without the endpoint, the user has to go into the 3rd party app, create a new record so that the 3rd party app sends Zapier a webhook, and hope that all of it happens within the window that Zapier subscribed for a notification (which is a short window when a user is simply testing a Zap during setup).

With a listing endpoint, Zapier can simply make one request and fetch an existing record.

A few things need to happen for full support:

1. [BasicHookOperation](https://github.com/zapier/zapier-platform-schema/blob/442214b5b3993082bba0fafa75182d112d7e7da7/lib/schemas/BasicHookOperationSchema.js) needs a new property to configure the endpoint. The best bet is probably a property like `performList` that is a `FunctionSchema`
1. Update the documentation to make sure it is clear that the existing [perform](https://github.com/zapier/zapier-platform-schema/blob/442214b5b3993082bba0fafa75182d112d7e7da7/lib/schemas/BasicHookOperationSchema.js#L26-L29) is used to process incoming webhooks and the new property is for making outbound requests to get samples
1. Zapier itself will need to be updated to know how to dispatch to each of those appropriately

**Comment by bryanhelmig** [comment]
The broader idea was that you would do resources and provide both a `hook` and `list` if you wanted to do this - but I can see how folks would want to provide standalone (non-resource) triggers that do both hook/poll.

I think `performList` is totally feasible - but we should clarify that if you are reaching for that you might look into `resources.*.hook/list` as an alternative!

**Comment by bryanhelmig** [comment]
Also, you might add a fourth bullet point to "backfill `performList` when converting resources".

**Comment by bryanhelmig** [comment]
Bumping the schema with this features to `0.9.12`.

**Comment by bcooksey** [comment]
Support has been added.
