### ISSUE TITLE
Should the naming collision around "dynamic" and "fields" be resolved?

### ISSUE THREAD

**Issue by bcooksey** [zapier/zapier-platform-schema#4]
There is a property on a field called [dynamic](https://github.com/zapier/zapier-platform-schema/blob/442214b5b3993082bba0fafa75182d112d7e7da7/lib/schemas/FieldSchema.js#L69-L72) which is where you specify the details to build a Dynamic Dropdown.

Then we have the [DynamicFieldsSchema](https://github.com/zapier/zapier-platform-schema/blob/442214b5b3993082bba0fafa75182d112d7e7da7/lib/schemas/DynamicFieldsSchema.js) and now a new [altersDynamicFields](https://github.com/zapier/zapier-platform-schema/blob/ed2ec72b5a809fd7de940ceca2568f63e765f510/lib/schemas/FieldSchema.js#L97-L100) which is all about dynamically loading more field definitions.

Something we should think about before 1.0 release is if one of those needs to be renamed.

**Comment by bryanhelmig** [comment]
I'd be fine renaming `DynamicFieldsSchema` to `CustomFieldsSchema` - though in isolation they are both pretty good names - just together they are slightly different things...

**Comment by bcooksey** [comment]
Since the fieldset can be static fields as well as fields computed from functions (be that API calls for custom fields, or simply a function that changes the static choices of a field based on some other field in the set), I think DynamicFieldsSchema actually fits well.

I say let's either go the route of [renaming dynamic](https://github.com/zapier/zapier-platform-schema/issues/2#issuecomment-279065727) property on the field, or call this good.

**Comment by BrunoBernardino** [comment]
I think it's good as it is. If we're renaming something. I'd prefer `altersDynamicFields` to `altersVisibleFields` or `altersInputFields` as it seems more explicit as to what it does.

**Comment by bcooksey** [comment]
Ok, let's not mess with it for now then.
