### ISSUE TITLE
Replace getResourceOperation with performGet?

### ISSUE THREAD

**Issue by bryanhelmig** [zapier/zapier-platform-schema#6]
As discussed with @bcooksey.

Since we're going with `performList` to connect a hook to a resource.list - I feel like we might make `performGet` match that pattern to replace `getResourceOperation`.

This will definitely be a breaking change! Can slip it into https://github.com/zapier/zapier-platform-core/pull/9.

**Comment by bryanhelmig** [comment]
I'll add the code to start making this work - we won't merge it quite yet until we're 100% on the change. It requires a bit of work:

1. Splitting Basic Operation schema out so that create, search operations can have `performGet`.
2. Removing all code and references to `getResourceOperation`.
3. Core will need to backfill zapier/zapier-platform-core#9.

**Comment by bryanhelmig** [comment]
Tracking schema changes in https://github.com/zapier/zapier-platform-schema/pull/7.

**Comment by bcooksey** [comment]
PR Shipped!
