### ISSUE TITLE
Should `resource` property be moved out of operation and up to the trigger/search/create

### ISSUE THREAD

**Issue by bcooksey** [zapier/zapier-platform-schema#8]
Once #7 lands, we'll have two different operations possible for triggers/searches/action. That means two places where you have to specify the resource. Not only is the duplication annoying, it'd be a pretty big deal to specify *different* resources for each of those. I'm having a hard time thinking of where that would be a good thing.

Further, the `noun` property lives up a level on the trigger/search/action. However, resources require a `noun` as well, so we should be able to pull that from the resource if we link a trigger to a resource.

All of this seems to point to the idea that the `resource` property should be moved out from under the operation and instead placed up a level at the trigger/search/create. The one downside is that it's on the operation that we define the `outputFields` and `sample`, so either way we will have to auto-populate data at two different levels in the schema when we pull from a resource.

**Comment by bcooksey** [comment]
Is this worth it @bryanhelmig @BrunoBernardino @benzapier (or anyone else who has context on CLI apps)?

**Comment by bryanhelmig** [comment]
So, the suggestion is:


```javascript
{
  "resources": {
    ...
  },
  "creates": {
    "contact_create": {
      "key": "contact_create",
      "noun": "Contact",
      "display": {
        "label": "Create Contact",
        "description": "Create a new Contact in your account."
      },
      "resource": "contact", // NEW PlACE
      "operation": {
        "perform": "$func$2$f$",
        "resource": "contact" // OLD PlACE
      }
    }
  }
}
```

Yes?

**Comment by BrunoBernardino** [comment]
I understood it the same as @bryanhelmig and while I can't fully understand _why_ the current placing is bad (where are the two places I have to define the resources that I won't after the change?), I trust your judgement on this.

Thinking of it as basic information architecture, the "resource" is what's being obtained for the "operation" in the "create", so being inside makes more contextual sense, _at a glance_. However, it also makes sense the "resource" is a representation of what will be obtained for that "create", so ¯\\_(ツ)_/¯

**Comment by bcooksey** [comment]
Thank you @bryanhelmig, I should have used a code example. You are correct.

Also, I'm not sure what I was thinking with the two places to define it. I'd been working on the code that copies stuff off resources all day, so I got some wires crossed when I made the ticket. That said, this is now less of a concern to me, but it might still be helpful so that folks don't have to re-define the noun each time.

**Comment by bryanhelmig** [comment]
I kind of think it should stay in `operation` - the reasoning is that `operation` was supposed to encapsulate the behavior & functionality - especially anything that isn't declarative like nouns, labels, etc.

**Comment by BrunoBernardino** [comment]
Re-defining a noun doesn't sound so bad, honestly. The alternative is making the noun conditionally optional which is a lot of complexity for this, I think, right?

**Comment by bcooksey** [comment]
Ok, let's hold off on this.
